### ISSUE TITLE
Haml issue causing downstream errors

### ISSUE THREAD

**Issue by dchandekstark** [ruby-rdf/rdf-rdfa#22]
Due to https://github.com/haml/haml/issues/695 -- and the fact that it has not been patched in a released version of Haml -- usage of rdf-rdfa is causing errors, e.g.:

```
/Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb:3:in `<module:Haml>': uninitialized constant Haml::ActionView (NameError)
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb:1:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml/railtie.rb:21:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml.rb:23:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfa-1.99.1/lib/rdf/rdfa/writer.rb:1:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfxml-1.99.0/lib/rdf/rdfxml/writer.rb:50:in `<module:RDFXML>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfxml-1.99.0/lib/rdf/rdfxml/writer.rb:3:in `<top (required)>'
```

Should this problem be patched here or push for a patched release of Haml?

**Comment by gkellogg** [comment]
Seems like Haml should release a patch. If this seems like it's delayed in coming, a monkey-patch (checking to see if it's defined first) would be reasonable, but perhaps you want to do this in Hydra.

**Comment by dchandekstark** [comment]
OK, thanks, will close this issue
